# Generated by Django 3.1 on 2020-08-06 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200806_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
